# Ativa o console web do banco H2
spring.h2.console.enabled=true
# Define o caminho para acessar o banco no navegador
spring.h2.console.path=/h2-console
# Define o link fixo do banco de dados na memória
spring.datasource.url=jdbc:h2:mem:bibliotecadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=